/*
 * Generates every icon asset of titan-ssh from branding/icon.svg.
 *
 * Single-file program with no dependencies, run from the repository root with
 * any JDK 17+:
 *
 *     java branding/RenderIcon.java
 *
 * The SVG is deliberately restricted to <rect> elements (see its header), so it
 * is parsed here directly instead of pulling in an SVG rasteriser. The outputs
 * are committed; rerun this program after changing the SVG.
 */

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class RenderIcon {

    /** Side of the SVG viewBox; the glyph is centred on (VIEW / 2, VIEW / 2). */
    static final double VIEW = 512;

    /** Android adaptive icon: 108dp canvas whose safe zone is a 66dp circle. */
    static final double ADAPTIVE_CANVAS = 108;
    static final double ADAPTIVE_SAFE_RADIUS = 33;

    static final int[] ICO_SIZES = {16, 20, 24, 32, 40, 48, 64, 128, 256};
    static final int[] PNG_SIZES = {16, 24, 32, 48, 64, 128, 256, 512};

    record Box(String id, double x, double y, double w, double h, double rx,
               Color fill, Color stroke, double strokeWidth) {}

    public static void main(String[] args) throws Exception {
        Path root = Path.of(args.length > 0 ? args[0] : ".");
        List<Box> boxes = parse(root.resolve("branding/icon.svg"));
        Box plate = boxes.stream().filter(b -> b.id().equals("plate")).findFirst()
                .orElseThrow(() -> new IllegalStateException("icon.svg has no rect id=\"plate\""));
        List<Box> glyph = boxes.stream().filter(b -> b != plate).toList();

        // Desktop: Windows installer icon, Linux installer icon and window icon.
        Path desktop = root.resolve("desktopApp");
        List<byte[]> icoImages = new ArrayList<>();
        for (int size : ICO_SIZES) icoImages.add(png(renderIcon(plate, glyph, size)));
        write(desktop.resolve("icons/titan-ssh.ico"), ico(ICO_SIZES, icoImages));
        write(desktop.resolve("icons/titan-ssh.png"), png(renderIcon(plate, glyph, 512)));
        write(desktop.resolve("src/main/resources/titan-ssh.png"), png(renderIcon(plate, glyph, 256)));

        // Loose PNG sizes for the freedesktop hicolor theme (Flatpak, AUR, ...).
        Path generated = root.resolve("branding/generated");
        for (int size : PNG_SIZES) {
            write(generated.resolve("png/titan-ssh-" + size + ".png"), png(renderIcon(plate, glyph, size)));
        }

        // Store listing (IzzyOnDroid, Play): full-bleed square icon and feature graphic.
        write(generated.resolve("store-icon-512.png"), png(renderSquare(plate, glyph, 512)));
        Font font = Font.createFont(Font.TRUETYPE_FONT,
                root.resolve("shared/src/commonMain/composeResources/font/jetbrainsmono_bold.ttf").toFile());
        write(generated.resolve("feature-graphic-1024x500.png"), png(renderFeature(plate, glyph, font)));

        // Android adaptive icon layers as vector drawables.
        Path res = root.resolve("androidApp/src/main/res");
        write(res.resolve("drawable/ic_launcher_foreground.xml"), vector(glyph, null));
        write(res.resolve("drawable/ic_launcher_monochrome.xml"), vector(glyph, Color.WHITE));
        write(res.resolve("values/ic_launcher_background.xml"), (
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
                        + "<!-- Generated by branding/RenderIcon.java from branding/icon.svg. Do not edit. -->\n"
                        + "<resources>\n"
                        + "    <color name=\"ic_launcher_background\">" + hex(plate.fill()) + "</color>\n"
                        + "</resources>\n").getBytes(StandardCharsets.UTF_8));

        System.out.println("Icon assets regenerated from branding/icon.svg");
    }

    static List<Box> parse(Path svg) throws Exception {
        var factory = DocumentBuilderFactory.newInstance();
        factory.setNamespaceAware(false);
        NodeList rects = factory.newDocumentBuilder().parse(svg.toFile()).getElementsByTagName("rect");
        List<Box> boxes = new ArrayList<>();
        for (int i = 0; i < rects.getLength(); i++) {
            Element e = (Element) rects.item(i);
            boxes.add(new Box(e.getAttribute("id"), num(e, "x"), num(e, "y"), num(e, "width"), num(e, "height"),
                    num(e, "rx"), color(e.getAttribute("fill")), color(e.getAttribute("stroke")),
                    num(e, "stroke-width")));
        }
        return boxes;
    }

    static double num(Element e, String name) {
        String v = e.getAttribute(name);
        return v.isEmpty() ? 0 : Double.parseDouble(v);
    }

    static Color color(String v) {
        return v.isEmpty() || v.equals("none") ? null : Color.decode(v);
    }

    static String hex(Color c) {
        return String.format(Locale.ROOT, "#%02X%02X%02X", c.getRed(), c.getGreen(), c.getBlue());
    }

    static Graphics2D graphics(BufferedImage image) {
        Graphics2D g = image.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        g.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        return g;
    }

    /** The icon as drawn in the SVG: rounded plate on a transparent square. */
    static BufferedImage renderIcon(Box plate, List<Box> glyph, int size) {
        BufferedImage image = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = graphics(image);
        g.scale(size / VIEW, size / VIEW);
        var shape = new RoundRectangle2D.Double(plate.x(), plate.y(), plate.w(), plate.h(), plate.rx() * 2, plate.rx() * 2);
        g.setColor(plate.fill());
        g.fill(shape);
        if (plate.stroke() != null && plate.strokeWidth() > 0) {
            g.setColor(plate.stroke());
            g.setStroke(new BasicStroke((float) plate.strokeWidth()));
            g.draw(shape);
        }
        drawGlyph(g, glyph);
        g.dispose();
        return image;
    }

    /** Full-bleed square for stores, which apply their own mask. */
    static BufferedImage renderSquare(Box plate, List<Box> glyph, int size) {
        BufferedImage image = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = graphics(image);
        g.setColor(plate.fill());
        g.fillRect(0, 0, size, size);
        g.scale(size / VIEW, size / VIEW);
        drawGlyph(g, glyph);
        g.dispose();
        return image;
    }

    static BufferedImage renderFeature(Box plate, List<Box> glyph, Font font) {
        int w = 1024, h = 500;
        BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = graphics(image);
        g.setColor(plate.fill());
        g.fillRect(0, 0, w, h);

        double glyphSize = 400;
        var saved = g.getTransform();
        g.translate(60, (h - glyphSize) / 2);
        g.scale(glyphSize / VIEW, glyphSize / VIEW);
        drawGlyph(g, glyph);
        g.setTransform(saved);

        Color ink = glyph.get(0).fill();
        g.setFont(font.deriveFont(88f));
        g.setColor(ink);
        FontMetrics m = g.getFontMetrics();
        int baseline = (h + m.getAscent() - m.getDescent()) / 2;
        g.drawString("titan-ssh", 470, baseline);
        g.dispose();
        return image;
    }

    /** Same-colour rects are merged into one shape so antialiasing leaves no seam where they touch. */
    static void drawGlyph(Graphics2D g, List<Box> glyph) {
        Map<Color, Area> areas = new LinkedHashMap<>();
        for (Box b : glyph) {
            areas.computeIfAbsent(b.fill(), k -> new Area()).add(new Area(new Rectangle2D.Double(b.x(), b.y(), b.w(), b.h())));
        }
        areas.forEach((color, area) -> {
            g.setColor(color);
            g.fill(area);
        });
    }

    /** Glyph rescaled so that its farthest corner sits on the adaptive safe-zone circle. */
    static byte[] vector(List<Box> glyph, Color tint) {
        double c = VIEW / 2, radius = 0;
        for (Box b : glyph) {
            for (double x : new double[] {b.x(), b.x() + b.w()}) {
                for (double y : new double[] {b.y(), b.y() + b.h()}) {
                    radius = Math.max(radius, Math.hypot(x - c, y - c));
                }
            }
        }
        double s = ADAPTIVE_SAFE_RADIUS / radius, o = ADAPTIVE_CANVAS / 2;
        StringBuilder xml = new StringBuilder()
                .append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
                .append("<!-- Generated by branding/RenderIcon.java from branding/icon.svg. Do not edit. -->\n")
                .append("<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n")
                .append("    android:width=\"108dp\"\n")
                .append("    android:height=\"108dp\"\n")
                .append("    android:viewportWidth=\"108\"\n")
                .append("    android:viewportHeight=\"108\">\n");
        // One <path> per colour, as in drawGlyph, so touching rects leave no seam.
        Map<String, StringBuilder> paths = new LinkedHashMap<>();
        for (Box b : glyph) {
            double x = o + (b.x() - c) * s, y = o + (b.y() - c) * s;
            StringBuilder data = paths.computeIfAbsent(hex(tint != null ? tint : b.fill()), k -> new StringBuilder());
            if (data.length() > 0) data.append(' ');
            data.append(String.format(Locale.ROOT, "M%.3f,%.3f h%.3f v%.3f h%.3f z",
                    x, y, b.w() * s, b.h() * s, -b.w() * s));
        }
        paths.forEach((color, data) -> xml.append(String.format(Locale.ROOT,
                "    <path\n        android:fillColor=\"%s\"\n        android:pathData=\"%s\" />\n", color, data)));
        return xml.append("</vector>\n").toString().getBytes(StandardCharsets.UTF_8);
    }

    static byte[] png(BufferedImage image) throws IOException {
        var out = new ByteArrayOutputStream();
        ImageIO.write(image, "png", out);
        return out.toByteArray();
    }

    /** ICO container with PNG-compressed entries (supported since Windows Vista). */
    static byte[] ico(int[] sizes, List<byte[]> images) {
        int header = 6 + 16 * sizes.length;
        int total = header + images.stream().mapToInt(i -> i.length).sum();
        ByteBuffer buf = ByteBuffer.allocate(total).order(ByteOrder.LITTLE_ENDIAN);
        buf.putShort((short) 0).putShort((short) 1).putShort((short) sizes.length);
        int offset = header;
        for (int i = 0; i < sizes.length; i++) {
            int size = sizes[i];
            buf.put((byte) (size >= 256 ? 0 : size)).put((byte) (size >= 256 ? 0 : size));
            buf.put((byte) 0).put((byte) 0);
            buf.putShort((short) 1).putShort((short) 32);
            buf.putInt(images.get(i).length).putInt(offset);
            offset += images.get(i).length;
        }
        images.forEach(buf::put);
        return buf.array();
    }

    static void write(Path path, byte[] bytes) throws IOException {
        Files.createDirectories(path.getParent());
        Files.write(path, bytes);
    }
}
