import java.security.MessageDigest
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKotlinMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// --- Level-3 agent (titan-agent) multi-arch build → bundled resources ----------
//
// Cross-compiles the Go agent in `agent/` for every destination target of
// ADR-0009 §6. ADR-0010 splits them: the main ones are bundled as JVM resources
// (under /agent/), the rest are published with the GitHub Release and
// downloaded on demand. Either way the app carries /agent/SHA256SUMS, the
// digest of every target, and never runs a download that does not match it.
//
// In development it is best-effort: if the Go toolchain is not found the build
// still succeeds with no binaries bundled, and a `ResilienceLevel.AGENT` session
// simply degrades to level 2/1 (AgentInstaller returns Unsupported). A release
// build (any version other than the dev one) must build every target, so a
// missing Go or a failed cross-compile fails it instead of shipping a package
// without level 3.
//
// -PtitanAgentPrebuilt=<dir> takes the binaries from a directory of Release
// assets (`titan-agent-<version>-<os>-<arch>[.exe]`) instead of compiling them.
// CI builds them once and hands the same files to every package, so the
// digests pinned in each app are exactly those of the published assets.
//
// The agent carries the single app version (root build file): it is stamped
// into the binary with -ldflags and drives the versioned install path.
val titanVersion = rootProject.extra["titanVersion"] as String
val agentModuleDir = rootProject.file("agent")
val agentBinariesDir = layout.buildDirectory.dir("generated/agentBinaries")
val agentAllDir = layout.buildDirectory.dir("agentBinaries/all")
val agentReleaseDir = layout.buildDirectory.dir("agentBinaries/release")
val agentPrebuiltDir = (findProperty("titanAgentPrebuilt") as String?)?.let { rootProject.file(it) }

/** A destination the agent is compiled for; [bundled] ones ship inside the app. */
data class AgentBuildTarget(val os: String, val arch: String, val bundled: Boolean) {
    val suffix: String get() = if (os == "windows") ".exe" else ""
    /** Build output and resource name; AgentTarget.fileName in the app. */
    val fileName: String get() = "titan-agent-$os-$arch$suffix"
    /** Release asset name; AgentDownloader.assetName in the app. */
    fun assetName(version: String): String = "titan-agent-$version-$os-$arch$suffix"
}

val agentTargets = listOf(
    AgentBuildTarget("linux", "amd64", bundled = true),
    AgentBuildTarget("linux", "arm64", bundled = true),
    AgentBuildTarget("darwin", "amd64", bundled = true),
    AgentBuildTarget("darwin", "arm64", bundled = true),
    AgentBuildTarget("windows", "amd64", bundled = true),
    AgentBuildTarget("windows", "arm64", bundled = true),
    AgentBuildTarget("linux", "arm", bundled = false),
    AgentBuildTarget("linux", "386", bundled = false),
    AgentBuildTarget("linux", "riscv64", bundled = false),
    AgentBuildTarget("linux", "ppc64le", bundled = false),
    AgentBuildTarget("linux", "s390x", bundled = false),
    AgentBuildTarget("freebsd", "amd64", bundled = false),
    AgentBuildTarget("freebsd", "arm64", bundled = false),
)

fun resolveGo(): String? {
    val candidates = listOfNotNull(
        System.getenv("GO"),
        System.getenv("GOROOT")?.let { "$it/bin/go" },
        "go",
        "C:\\Program Files\\Go\\bin\\go.exe",
        "/usr/local/go/bin/go",
        "/usr/bin/go",
    )
    for (c in candidates) {
        try {
            val p = ProcessBuilder(c, "version").redirectErrorStream(true).start()
            if (p.waitFor() == 0) return c
        } catch (_: Exception) { /* try next */ }
    }
    return null
}

// --- Build info and legal texts for the About screen ---------------------------
//
// BuildInfo exposes the single app version to commonMain. The root LICENSE and
// THIRD_PARTY_NOTICES.md are bundled as JVM resources under /legal/ so the About
// screen shows them offline, from the same files the repository publishes.
val buildInfoDir = layout.buildDirectory.dir("generated/buildInfo/commonMain/kotlin")
val generateBuildInfo by tasks.registering {
    description = "Generates BuildInfo.kt with the single app version."
    inputs.property("titanVersion", titanVersion)
    outputs.dir(buildInfoDir)
    doLast {
        val file = buildInfoDir.get()
            .file("io/github/danielperezmartinez/titanssh/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package io.github.danielperezmartinez.titanssh
            |
            |/** Generated by the `generateBuildInfo` Gradle task; do not edit. */
            |object BuildInfo {
            |    /** Single app version (root build file), `0.0.0-dev` outside a release. */
            |    const val VERSION: String = "$titanVersion"
            |
            |    /** False for a development build (no release version was resolved). */
            |    const val IS_RELEASE: Boolean = ${titanVersion != "0.0.0-dev"}
            |}
            |""".trimMargin(),
        )
    }
}

val legalTextsDir = layout.buildDirectory.dir("generated/legalTexts")
val bundleLegalTexts by tasks.registering(Copy::class) {
    description = "Bundles LICENSE and THIRD_PARTY_NOTICES.md as resources for the About screen."
    from(rootProject.file("LICENSE"), rootProject.file("THIRD_PARTY_NOTICES.md"))
    into(legalTextsDir.map { it.dir("legal") })
}

kotlin {
    // Android target as a KMP library (AGP 9 native plugin
    // com.android.kotlin.multiplatform.library), so it coexists with
    // kotlin.multiplatform without the legacy com.android.library + compat flags.
    android {
        namespace = "io.github.danielperezmartinez.titanssh.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        // Compose resources (the bundled JetBrains Mono) reach an Android app
        // only as assets, and this library plugin packages none unless Android
        // resources are on. Without it every Font() silently fell back to the
        // proportional system font on Android.
        androidResources {
            enable = true
        }

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // Desktop (Windows/Linux) target.
    jvm("desktop") {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            // Bundled fonts (JetBrains Mono) via Compose Multiplatform resources.
            // "Mono en todo" is the visual identity; the family is bundled rather
            // than relying on the system monospace.
            implementation(compose.components.resources)
            implementation(libs.kotlinx.coroutines.core)
            // Config model + persistence (hosts/sessions/scripts) serialized to
            // JSON. The @Serializable types live in commonMain; the file-backed
            // store lives in jvmShared.
            implementation(libs.kotlinx.serialization.json)
        }

        // Intermediate JVM source set shared by Android and desktop (README
        // architecture): pure-Java pieces both JVM targets use, notably the sshj
        // SSH client (ADR-0004). commonMain stays free of sshj.
        val jvmSharedMain = create("jvmSharedMain") {
            dependsOn(getByName("commonMain"))
            dependencies {
                implementation(libs.sshj)
                implementation(libs.eddsa)
            }
        }

        getByName("androidMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                // Full BouncyCastle so sshj can negotiate with modern OpenSSH on
                // Android (its bundled "BC" provider is stripped down). ADR-0004.
                implementation(libs.bouncycastle.prov)
            }
        }

        // Desktop SecretStore backend (ADR-0001). Android uses the platform
        // KeyStore directly, so this dependency is desktop-only.
        getByName("desktopMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                implementation(libs.java.keyring)
            }
        }

        getByName("desktopTest").dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }

        // The level-3 agent binaries (ADR-0008) are built by `buildAgentBinaries`
        // into a generated resources dir and packaged as JVM resources under
        // /agent/, so both the desktop app and the Android app can ship them and
        // install them on the destination on first use (AgentInstaller). Loaded via
        // the classloader by AgentBinaries.
        getByName("jvmSharedMain").resources.srcDir(agentBinariesDir)
        getByName("jvmSharedMain").resources.srcDir(legalTextsDir)
        getByName("commonMain").kotlin.srcDir(generateBuildInfo)
    }
}

val agentRequired = rootProject.extra["titanIsRelease"] as Boolean

val buildAgentBinaries by tasks.registering {
    description = "Builds titan-agent (level-3) for every target, bundles the main ones and pins every digest."
    if (agentPrebuiltDir != null) inputs.dir(agentPrebuiltDir) else inputs.dir(agentModuleDir)
    inputs.property("titanVersion", titanVersion)
    inputs.property("agentTargets", agentTargets.map { "${it.fileName}:${it.bundled}" })
    outputs.dir(agentBinariesDir)
    outputs.dir(agentAllDir)
    doLast {
        // Development: warn and bundle what could be built. Release: fail.
        fun problem(message: String) {
            if (agentRequired) throw GradleException("$message (a release build must include the level-3 agent)")
            logger.warn(message)
        }
        val allDir = agentAllDir.get().asFile
        val resDir = agentBinariesDir.get().dir("agent").asFile
        listOf(allDir, resDir).forEach { it.deleteRecursively(); it.mkdirs() }

        if (agentPrebuiltDir != null) {
            agentTargets.forEach { t ->
                val src = File(agentPrebuiltDir, t.assetName(titanVersion))
                if (src.isFile) src.copyTo(File(allDir, t.fileName))
                else problem("titan-agent: prebuilt ${src.name} not found in $agentPrebuiltDir")
            }
        } else {
            val go = resolveGo()
            if (go == null) {
                problem("titan-agent: Go toolchain not found; level-3 agent binaries NOT bundled (AGENT sessions will degrade to level 2/1).")
                return@doLast
            }
            agentTargets.forEach { t ->
                val failure = try {
                    val pb = ProcessBuilder(
                        go, "build", "-trimpath", "-ldflags", "-s -w -X main.version=$titanVersion",
                        "-o", File(allDir, t.fileName).absolutePath, "./cmd/titan-agent",
                    )
                    pb.directory(agentModuleDir)
                    // Static, self-contained binaries: nothing to install on the destination.
                    pb.environment()["CGO_ENABLED"] = "0"
                    pb.environment()["GOOS"] = t.os
                    pb.environment()["GOARCH"] = t.arch
                    // 32-bit ARM: ARMv7 (Raspberry Pi 2 and later, most boards).
                    if (t.arch == "arm") pb.environment()["GOARM"] = "7"
                    pb.redirectErrorStream(true)
                    val process = pb.start()
                    val log = process.inputStream.bufferedReader().readText()
                    val code = process.waitFor()
                    if (code != 0) "titan-agent: cross-compile failed for ${t.os}/${t.arch} (exit $code): ${log.take(500)}" else null
                } catch (e: Exception) {
                    "titan-agent: cross-compile error for ${t.os}/${t.arch}: ${e.message}"
                }
                failure?.let(::problem)
            }
        }

        // Bundle the main targets and pin the digest of every one (ADR-0010).
        val sums = StringBuilder()
        agentTargets.forEach { t ->
            val file = File(allDir, t.fileName)
            if (!file.isFile) return@forEach
            val digest = MessageDigest.getInstance("SHA-256").digest(file.readBytes())
            sums.append(digest.joinToString("") { "%02x".format(it) }).append("  ").append(t.fileName).append('\n')
            if (t.bundled) file.copyTo(File(resDir, t.fileName))
        }
        if (sums.isNotEmpty()) File(resDir, "SHA256SUMS").writeText(sums.toString())
    }
}

// Every agent binary under its Release asset name, for the release pipeline:
// published with the Release (the on-demand targets are downloaded from there)
// and handed back to the packaging jobs through -PtitanAgentPrebuilt.
val agentReleaseAssets by tasks.registering(Copy::class) {
    description = "Copies every titan-agent binary under its GitHub Release asset name."
    dependsOn(buildAgentBinaries)
    from(agentAllDir)
    into(agentReleaseDir)
    rename { name -> agentTargets.first { it.fileName == name }.assetName(titanVersion) }
}

// Make every resource-processing/packaging task depend on the agent build, so the
// binaries and legal texts are present whenever resources are assembled
// (desktop jar, Android apk).
tasks.matching {
    it.name.contains("ProcessResources", ignoreCase = true) ||
        it.name.contains("JavaRes", ignoreCase = true)
}.configureEach { dependsOn(buildAgentBinaries, bundleLegalTexts) }

// Generate a stable, importable accessor (`io.github.danielperezmartinez.titanssh.resources.Res`) for
// the bundled Compose resources (JetBrains Mono fonts).
compose.resources {
    publicResClass = true
    packageOfResClass = "io.github.danielperezmartinez.titanssh.resources"
}

// Opt-in integration tests reach a real SSH host. Connection details are passed
// as -P project properties (never committed) and forwarded to the test JVM as
// env vars; SshjIntegrationTest skips itself when they are absent.
tasks.withType<Test>().configureEach {
    testLogging { showStandardStreams = true }
    mapOf(
        "titanSshTestHost" to "TITAN_SSH_TEST_HOST",
        "titanSshTestPort" to "TITAN_SSH_TEST_PORT",
        "titanSshTestUser" to "TITAN_SSH_TEST_USER",
        "titanSshTestKey" to "TITAN_SSH_TEST_KEY",
        "titanSshTestPassphrase" to "TITAN_SSH_TEST_PASSPHRASE",
        // "true" when the test host has AllowTcpForwarding off, for the
        // refusal checks of SshjForwardingIntegrationTest.
        "titanSshTestNoForwarding" to "TITAN_SSH_TEST_NO_FORWARDING",
        // Path to a built titan-agent binary matching the test host's arch, for
        // AgentInstallerIntegrationTest (level-3 agent install, ADR-0008).
        "titanAgentBin" to "TITAN_AGENT_BIN",
    ).forEach { (prop, env) ->
        (project.findProperty(prop) as String?)?.let { environment(env, it) }
    }
}
