import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKotlinMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// --- Level-3 agent (titan-agent) multi-arch build → bundled resources ----------
//
// Cross-compiles the Go agent in `agent/` for each destination target into JVM
// resources (packaged under /agent/). Best-effort: if the Go toolchain is not
// found the build still succeeds with no binaries bundled, and a
// `ResilienceLevel.AGENT` session simply degrades to level 2/1 (AgentInstaller
// returns Unsupported). See ADR-0008.
//
// The agent carries the single app version (root build file): it is stamped
// into the binary with -ldflags and drives the versioned install path.
val titanVersion = rootProject.extra["titanVersion"] as String
val agentModuleDir = rootProject.file("agent")
val agentBinariesDir = layout.buildDirectory.dir("generated/agentBinaries")
val agentTargets = listOf("linux" to "amd64", "linux" to "arm64", "darwin" to "arm64")

fun resolveGo(): String? {
    val candidates = listOfNotNull(
        System.getenv("GO"),
        System.getenv("GOROOT")?.let { "$it/bin/go" },
        "go",
        "C:\\Program Files\\Go\\bin\\go.exe",
        "/usr/local/go/bin/go",
        "/usr/bin/go",
    )
    for (c in candidates) {
        try {
            val p = ProcessBuilder(c, "version").redirectErrorStream(true).start()
            if (p.waitFor() == 0) return c
        } catch (_: Exception) { /* try next */ }
    }
    return null
}

// --- Build info and legal texts for the About screen ---------------------------
//
// BuildInfo exposes the single app version to commonMain. The root LICENSE and
// THIRD_PARTY_NOTICES.md are bundled as JVM resources under /legal/ so the About
// screen shows them offline, from the same files the repository publishes.
val buildInfoDir = layout.buildDirectory.dir("generated/buildInfo/commonMain/kotlin")
val generateBuildInfo by tasks.registering {
    description = "Generates BuildInfo.kt with the single app version."
    inputs.property("titanVersion", titanVersion)
    outputs.dir(buildInfoDir)
    doLast {
        val file = buildInfoDir.get()
            .file("io/github/danielperezmartinez/titanssh/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package io.github.danielperezmartinez.titanssh
            |
            |/** Generated by the `generateBuildInfo` Gradle task; do not edit. */
            |object BuildInfo {
            |    /** Single app version (root build file), `0.0.0-dev` outside a release. */
            |    const val VERSION: String = "$titanVersion"
            |
            |    /** False for a development build (no release version was resolved). */
            |    const val IS_RELEASE: Boolean = ${titanVersion != "0.0.0-dev"}
            |}
            |""".trimMargin(),
        )
    }
}

val legalTextsDir = layout.buildDirectory.dir("generated/legalTexts")
val bundleLegalTexts by tasks.registering(Copy::class) {
    description = "Bundles LICENSE and THIRD_PARTY_NOTICES.md as resources for the About screen."
    from(rootProject.file("LICENSE"), rootProject.file("THIRD_PARTY_NOTICES.md"))
    into(legalTextsDir.map { it.dir("legal") })
}

kotlin {
    // Android target as a KMP library (AGP 9 native plugin
    // com.android.kotlin.multiplatform.library), so it coexists with
    // kotlin.multiplatform without the legacy com.android.library + compat flags.
    android {
        namespace = "io.github.danielperezmartinez.titanssh.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // Desktop (Windows/Linux) target.
    jvm("desktop") {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            // Bundled fonts (JetBrains Mono) via Compose Multiplatform resources.
            // "Mono en todo" is the visual identity; the family is bundled rather
            // than relying on the system monospace.
            implementation(compose.components.resources)
            implementation(libs.kotlinx.coroutines.core)
            // Config model + persistence (hosts/sessions/scripts) serialized to
            // JSON. The @Serializable types live in commonMain; the file-backed
            // store lives in jvmShared.
            implementation(libs.kotlinx.serialization.json)
        }

        // Intermediate JVM source set shared by Android and desktop (README
        // architecture): pure-Java pieces both JVM targets use, notably the sshj
        // SSH client (ADR-0004). commonMain stays free of sshj.
        val jvmSharedMain = create("jvmSharedMain") {
            dependsOn(getByName("commonMain"))
            dependencies {
                implementation(libs.sshj)
                implementation(libs.eddsa)
            }
        }

        getByName("androidMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                // Full BouncyCastle so sshj can negotiate with modern OpenSSH on
                // Android (its bundled "BC" provider is stripped down). ADR-0004.
                implementation(libs.bouncycastle.prov)
            }
        }

        // Desktop SecretStore backend (ADR-0001). Android uses the platform
        // KeyStore directly, so this dependency is desktop-only.
        getByName("desktopMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                implementation(libs.java.keyring)
            }
        }

        getByName("desktopTest").dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }

        // The level-3 agent binaries (ADR-0008) are built by `buildAgentBinaries`
        // into a generated resources dir and packaged as JVM resources under
        // /agent/, so both the desktop app and the Android app can ship them and
        // install them on the destination on first use (AgentInstaller). Loaded via
        // the classloader by AgentBinaries.
        getByName("jvmSharedMain").resources.srcDir(agentBinariesDir)
        getByName("jvmSharedMain").resources.srcDir(legalTextsDir)
        getByName("commonMain").kotlin.srcDir(generateBuildInfo)
    }
}

val buildAgentBinaries by tasks.registering {
    description = "Cross-compiles titan-agent (level-3) for each destination target into bundled resources."
    inputs.dir(agentModuleDir)
    inputs.property("titanVersion", titanVersion)
    outputs.dir(agentBinariesDir)
    doLast {
        val outDir = agentBinariesDir.get().dir("agent").asFile
        outDir.mkdirs()
        val go = resolveGo()
        if (go == null) {
            logger.warn("titan-agent: Go toolchain not found; level-3 agent binaries NOT bundled (AGENT sessions will degrade to level 2/1).")
            return@doLast
        }
        agentTargets.forEach { (os, arch) ->
            val out = File(outDir, "titan-agent-$os-$arch")
            try {
                val pb = ProcessBuilder(
                    go, "build", "-trimpath", "-ldflags", "-s -w -X main.version=$titanVersion",
                    "-o", out.absolutePath, "./cmd/titan-agent",
                )
                pb.directory(agentModuleDir)
                pb.environment()["GOOS"] = os
                pb.environment()["GOARCH"] = arch
                pb.redirectErrorStream(true)
                val process = pb.start()
                val log = process.inputStream.bufferedReader().readText()
                val code = process.waitFor()
                if (code != 0) {
                    logger.warn("titan-agent: cross-compile failed for $os/$arch (exit $code): ${log.take(500)}")
                }
            } catch (e: Exception) {
                logger.warn("titan-agent: cross-compile error for $os/$arch: ${e.message}")
            }
        }
    }
}

// Make every resource-processing/packaging task depend on the agent build, so the
// binaries and legal texts are present whenever resources are assembled
// (desktop jar, Android apk).
tasks.matching {
    it.name.contains("ProcessResources", ignoreCase = true) ||
        it.name.contains("JavaRes", ignoreCase = true)
}.configureEach { dependsOn(buildAgentBinaries, bundleLegalTexts) }

// Generate a stable, importable accessor (`io.github.danielperezmartinez.titanssh.resources.Res`) for
// the bundled Compose resources (JetBrains Mono fonts).
compose.resources {
    publicResClass = true
    packageOfResClass = "io.github.danielperezmartinez.titanssh.resources"
}

// Opt-in integration tests reach a real SSH host. Connection details are passed
// as -P project properties (never committed) and forwarded to the test JVM as
// env vars; SshjIntegrationTest skips itself when they are absent.
tasks.withType<Test>().configureEach {
    testLogging { showStandardStreams = true }
    mapOf(
        "titanSshTestHost" to "TITAN_SSH_TEST_HOST",
        "titanSshTestPort" to "TITAN_SSH_TEST_PORT",
        "titanSshTestUser" to "TITAN_SSH_TEST_USER",
        "titanSshTestKey" to "TITAN_SSH_TEST_KEY",
        "titanSshTestPassphrase" to "TITAN_SSH_TEST_PASSPHRASE",
        // Path to a built titan-agent binary matching the test host's arch, for
        // AgentInstallerIntegrationTest (level-3 agent install, ADR-0008).
        "titanAgentBin" to "TITAN_AGENT_BIN",
    ).forEach { (prop, env) ->
        (project.findProperty(prop) as String?)?.let { environment(env, it) }
    }
}
